#!/bin/bash

usage() {
    printf "Usage: picomutil <start|toggle|animation-toggle>\n"
    exit 1
}

kill() {
    killall -q picom
}

start() {
    picom --experimental-backends --config "$HOME/.config/awesome/external/picom/picom.conf" &
}

start_animations() {
    picom --animations --experimental-backends --config "$HOME/.config/awesome/external/picom/picom.conf" &
}

use_animations() {
    [ "$(cat $HOME/.cache/picomutil.animations)" == "true" ] && true || false
}

animations() {
    echo "$1" > "$HOME/.cache/picomutil.animations"
}

notif() {
    icon="placeholder"
    if [ $3 ]; then
        icon="$3"
    fi

    time="2000"
    if [ $4 ]; then
        icon="$4"
    fi

    # this hint allows the notification to replace previous confirmation notifications
    dunstify -h "string:x-canonical-private-synchronous:anything" -a "picomutil" -i "$icon" -u "normal" -t "$time" "$1" "$2"
}

if [[ ! $1 ]]; then
    usage
fi

case $1 in
    start)
        kill
        use_animations && start_animations || start
        ;;

    toggle)
        if pgrep -x picom > /dev/null; then
            kill
            notif "Compositor" "Picom disabled"
        else
            use_animations && start_animations || start
            notif "Compositor" "Picom enabled"
        fi
        ;;

    animation-toggle)
        kill

        if use_animations; then
            start

            animations "false"
            notif "Compositor" "Window animations disabled"
        else
            start_animations

            animations "true"
            notif "Compositor" "Window animations enabled"
        fi
        ;;

    *)
        usage
        ;;
esac
