#!/bin/bash

usage() {
    printf "Usage: picomutil <toggle|start>\n"
    exit 1
}

kill() {
    killall -q picom
}

start() {
    picom --config "$HOME/.config/awesome/external/picom/picom.conf" &
}

notif() {
    icon="placeholder"
    if [ $3 ]; then
        icon="$3"
    fi

    time="2000"
    if [ $4 ]; then
        icon="$4"
    fi

    # this hint allows the notification to replace previous confirmation notifications
    dunstify -h "string:x-canonical-private-synchronous:anything" -a "picomutil" -i "$icon" -u "normal" -t "$time" "$1" "$2"
}

if [[ ! $1 ]]; then
    usage
fi

case $1 in
    start)
        kill
        start
        ;;

    toggle)
        if pgrep -x picom > /dev/null; then
            kill
            notif "Compositor" "Picom disabled"
        else
            start
            notif "Compositor" "Picom enabled"
        fi
        ;;

    *)
        usage
        ;;
esac
